apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mobx-barkellato-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/noaabarki/mobx-barelato.git"
    targetRevision: HEAD
    path: kube/*.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mobx-barkellato-app
  syncPolicy:
    automated:
      selfHeal: true
