apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-2
  namespace: argocd
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: ["/bin/sh", "-c", "env"]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: eks1dot22plus
  restartPolicy: Never
