apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-research
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: mobx-barkellato
      server: https://kubernetes.default.svc

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist: []
