apiVersion: argoproj.io/v1alpha1
kind: Workflow # new type of k8s spec
metadata:
  name: "hello-world-workflow-v1-hello-world-workflow-v1-hello-world-workflow-v1-hello-world-workflow-v1"
  # generateName: hello-world- # name of the workflow spec
spec:
  entrypoint: everything # invoke the whalesay template
  templates:
    - name: everything
      steps:
        # - - name: whalesay # name of the template
        #     container:
        #       image: docker/whalesay
        #       command: [cowsay]
        #       args: ["hello world"]
        #       resources: # limit the resources
        #         limits:
        #           memory: 32Mi
        #           cpu: 100m

        - - name: generate
            template: gen-random-int-bash

        - - name: print
            template: print-output
            arguments:
              parameters:
                - name: message
                  value: "{{steps.generate.outputs.result}}" # The result of the here-script

    - name: gen-random-int-bash
      script:
        image: debian:9.4
        command: [bash]
        source: | # Contents of the here-script
          cat /dev/urandom | od -N2 -An -i | awk -v f=1 -v r=100 '{printf "%i\n", f + r * $1 / 65536}'

    - name: print-output
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo result was: {{inputs.parameters.message}}"]
